### ISSUE TITLE
Last job retry 

### ISSUE THREAD

**Issue by vmbro** [marcohorstmann/psscripts#2]
Hello, if a backup job succeeded at retries then report generates first job status. So i see these jobs as failed status but job succeeded on next tries. Would you modify this to check only last job status ?  Thanks.

**Comment by marcohorstmann** [comment]
@babychupchup contacted my via LinkedIn and I asked some question about the issue. I had overseen this issue.

**Comment by vmbro** [comment]
script sends me failed status but backup job successful on retry. Script doesnt check backup job last status

![my-veeam-report-summary](https://user-images.githubusercontent.com/6716206/142427711-fdb6242e-1199-40c2-b24e-8678f3f62a82.png)
![veeam-job-summary](https://user-images.githubusercontent.com/6716206/142427784-f63f1f77-08af-4527-96a4-bad5c801e98a.png)

**Comment by marcohorstmann** [comment]
Ah I think I unterstand. You talk about the MyVeeamReport Script right?

**Comment by vmbro** [comment]
Yess !!

**Comment by marcohorstmann** [comment]
ok, can you please forward me one of your emails. My lab has so many errors and warnings in it. You can send it to firstname.lastname@veeam.com. I need to see in which section  the code change is needed. Maybe you know that it's not my code I just keep it alive, because it seems that the original maintainer has abandoned it. Thx Marco

**Comment by marcohorstmann** [comment]
Hi,
talked to @babychupchup and he just needed to change this line:
$onlyLastBk = $false
to
$onlyLastBk = $true

With this line you only see the last backup session and not all failed sessions before.
